wikidata:
  name: Wikidata
  url: https://qlever.dev/api/wikidata
  default: false
  engine: QLever
  preset: [common_prefixes, qlever_default]
geocodesall:
  name: geocodesall
  url: https://qlever.geocodes-aws.earthcube.org/graphspace/geocodesall
  default: true
  engine: QLever
deepocean:
  name: deepocean
  url: https://qlever.geocodes-aws.earthcube.org/graphspace/deepoceans
  default: false
  engine: QLever
earthsurface:
  name: earthsurface
  url: https://qlever.geocodes-aws.earthcube.org/graphspace/earthsurface
  default: false
  engine: QLever
ecoforecast:
  name: Ecological Forecasting
  url: https://qlever.geocodes-aws.earthcube.org/graphspace/ecoforecast
  default: false
  engine: QLever
ecrr:
  name: EarthCube Research Resource Registry
  url: https://qlever.geocodes-aws.earthcube.org/graphspace/ecrr
  default: false
  engine: QLever

dev-facetsearch:
  name: dev-facetsearch
  url: https://qlever.geocodes-aws-dev.earthcube.org/graphspace/facetsearch
  default: true
  engine: QLever
dev-deepocean:
  name: dev-deepocean
  url: https://qlever.geocodes-aws-dev.earthcube.org/graphspace/deepoceans
  default: false
  engine: QLever

dev-ecoforecast:
  name: dev-EcoForecast
  url: https://qlever.geocodes-aws-dev.earthcube.org/graphspace/ecoforecast
  default: false
  engine: QLever
dev-ecrr:
  name: dev-EarthCube Research Resource Registry
  url: https://qlever.geocodes-aws-dev.earthcube.org/graphspace/ecrr
  default: false
  engine: QLever
dev-geocodesexamples:
  name: dev-Geocodes Demo Data
  url: https://qlever.geocodes-aws-dev.earthcube.org/graphspace/geocodesexamples
  default: false
  engine: QLever
dev-earthsurface:
  name: dev-EarthSurface
  url: https://qlever.geocodes-aws-dev.earthcube.org/graphspace/earthsurface
  default: false
  engine: QLever
dev-test:
  name: dev-test
  url: https://qlever.geocodes-aws-dev.earthcube.org/graphspace/test
  default: false
  engine: QLever
